AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  stackName:
    Description: Name for the stack
    Type: String

Resources:
  cardsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: cardsTable
      AttributeDefinitions:
        -
          AttributeName: cardId
          AttributeType: S
      KeySchema:
        -
          AttributeName: cardId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
      Tags:
        - Key: project-stack
          Value: !Join [ "-", [ !Ref stackName, "cardsTable" ]]

